// <auto-generated />
using ControlePagamentoEntidades.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlePagamentoEntidades.Migrations
{
    [DbContext(typeof(SistemaCPEContext))]
    [Migration("20221201172859_AtualizaTabelaserelacionamentos")]
    partial class AtualizaTabelaserelacionamentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControlePagamentoEntidades.Models.EntidadeModel", b =>
                {
                    b.Property<int>("EntidadeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntidadeID"), 1L, 1);

                    b.Property<string>("EntidadeCNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadeNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntidadeID");

                    b.ToTable("Entidades");
                });
#pragma warning restore 612, 618
        }
    }
}
